# Generated by Django 5.2.11 on 2026-05-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tokens", "0015_tokenlist_auth_key_tokenlist_auth_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="src20",
            field=models.BooleanField(
                default=False,
                help_text="Set `True` for SRC20 confidential tokens (amounts are encrypted)",
            ),
        ),
    ]
