# Generated by Django 5.2.11 on 2026-06-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0016_token_src20'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='src20_keyless_placeholder_logs_per_transfer',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of `encryptKeyHash == 0` `Transfer` logs a single SRC20 transfer emits when both parties are keyless (sender + recipient = 2 for the standard base). STRUCTURAL and PROVIDER-INDEPENDENT: provider logs carry non-zero hashes and are counted separately, so this value stays 2 even when providers are registered. Used as the divisor to collapse duplicate keyless logs back to one logical transfer. `1` means keep every log (never under-count).'),
        ),
    ]
