# Generated by Django 3.2.18 on 2023-05-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0074_fix_wrong_owners_20230620_0944"),
    ]

    operations = [
        # Add index on _from and block_number in InternalTx
        migrations.AddIndex(
            model_name="internaltx",
            index=models.Index(
                fields=["_from", "block_number"],
                name="history_int_from_block_idx",
            ),
        ),
        # Add index on the combined fields used in the slow query
        migrations.AddIndex(
            model_name="internaltxdecoded",
            index=models.Index(
                fields=["processed", "internal_tx_id"],
                name="history_dec_proc_itx_idx",
            ),
        ),
        # Add index to optimize the subquery performance - with included id column
        migrations.AddIndex(
            model_name="internaltx",
            index=models.Index(
                fields=["_from", "block_number"],
                name="history_int_from_blk_id_idx",
                include=["id"],
            ),
        ),
    ] 