# Generated by Django 5.0.12 on 2025-03-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0091_remove_notifications'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='internaltx',
            index=models.Index(fields=['_from', 'block_number'], include=('id',), name='history_internal_from_block_id'),
        ),
        migrations.AddIndex(
            model_name='internaltxdecoded',
            index=models.Index(fields=['processed', 'internal_tx_id'], name='history_decoded_processed_itx'),
        ),
    ]
