# Generated by hand on 2025-10-10 for Safe balance optimization
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from safe_eth.eth.django.models import Uint256Field


class Migration(migrations.Migration):

    dependencies = [
        ("history", "0093_alter_ethereumblock_timestamp"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtofireSafeBalance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "balance_wei",
                    Uint256Field(
                        default=0,
                        help_text="Native token balance in wei",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this balance was last fetched from blockchain",
                    ),
                ),
                (
                    "safe_contract",
                    models.OneToOneField(
                        help_text="The Safe contract this balance belongs to",
                        on_delete=models.deletion.CASCADE,
                        related_name="protofire_balance",
                        to="history.safecontract",
                    ),
                ),
            ],
            options={
                "db_table": "protofire_safe_balance",
                "ordering": ["-last_updated"],
            },
        ),
        migrations.AddIndex(
            model_name="protofiresafebalance",
            index=models.Index(fields=["balance_wei"], name="pf_safebal_balance_wei_idx"),
        ),
        migrations.AddIndex(
            model_name="protofiresafebalance",
            index=models.Index(fields=["last_updated"], name="pf_safebal_last_upd_idx"),
        ),
    ]