# Generated by Django 5.2.11 on 2026-10-04 21:44

import django.db.models.deletion
import safe_eth.eth.django.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Min

DELAY_MODULE_EVENTS = 1


def create_delay_module_indexing_status(apps, schema_editor):
    """
    Start indexing from the oldest Safe singleton deployment, so every Delay Modifier event
    emitted during the Safe era is backfilled
    """
    SafeMasterCopy = apps.get_model("history", "SafeMasterCopy")
    IndexingStatus = apps.get_model("history", "IndexingStatus")

    queryset = (
        SafeMasterCopy.objects.filter(l2=True)
        if settings.ETH_L2_NETWORK
        else SafeMasterCopy.objects.all()
    )
    block_number = (
        queryset.aggregate(block_number=Min("initial_block_number"))["block_number"]
        or 0
    )
    IndexingStatus.objects.get_or_create(
        indexing_type=DELAY_MODULE_EVENTS, defaults={"block_number": block_number}
    )


def remove_delay_module_indexing_status(apps, schema_editor):
    IndexingStatus = apps.get_model("history", "IndexingStatus")
    IndexingStatus.objects.filter(indexing_type=DELAY_MODULE_EVENTS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0100_safelaststatus_module_guard_safestatus_module_guard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexingstatus',
            name='indexing_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'ERC20_721_EVENTS'), (1, 'DELAY_MODULE_EVENTS')], primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DelayModuleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_index', models.PositiveIntegerField()),
                ('block_number', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('module', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('queue_nonce', safe_eth.eth.django.models.Uint256Field()),
                ('module_tx_hash', safe_eth.eth.django.models.Keccak256Field()),
                ('to', safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ('value', safe_eth.eth.django.models.Uint256Field()),
                ('data', models.BinaryField(null=True)),
                ('operation', models.PositiveSmallIntegerField(choices=[(0, 'CALL'), (1, 'DELEGATE_CALL'), (2, 'CREATE')])),
                ('ethereum_tx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.ethereumtx')),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'queue_nonce'], name='history_del_module_59a67e_idx')],
                'constraints': [models.UniqueConstraint(fields=('ethereum_tx', 'log_index'), name='unique_delay_module_transaction_index')],
            },
        ),
        migrations.RunPython(
            create_delay_module_indexing_status,
            reverse_code=remove_delay_module_indexing_status,
        ),
    ]
