# Generated by Django 5.2.11 on 2026-05-29 15:31

import django.db.models.deletion
from django.db import migrations, models

import safe_eth.eth.django.models

from ..models import IndexingStatusType


def create_src20_indexing_status(apps, schema_editor):
    """
    Seed the SRC20 indexing cursor. Start from the current ERC20/721 indexing block so it
    doesn't rescan the whole chain. Operators can lower it manually to backfill historical
    SRC20 transfers.
    """
    IndexingStatus = apps.get_model("history", "IndexingStatus")

    block_number = 0
    try:
        block_number = IndexingStatus.objects.get(
            indexing_type=IndexingStatusType.ERC20_721_EVENTS.value
        ).block_number
    except IndexingStatus.DoesNotExist:
        pass

    IndexingStatus.objects.update_or_create(
        indexing_type=IndexingStatusType.SRC20_EVENTS.value,
        defaults={"block_number": block_number},
    )


def remove_src20_indexing_status(apps, schema_editor):
    IndexingStatus = apps.get_model("history", "IndexingStatus")
    IndexingStatus.objects.filter(
        indexing_type=IndexingStatusType.SRC20_EVENTS.value
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0100_safelaststatus_module_guard_safestatus_module_guard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexingstatus",
            name="indexing_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "ERC20_721_EVENTS"), (1, "SRC20_EVENTS")],
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="SRC20Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("block_number", models.PositiveIntegerField()),
                ("address", safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ("_from", safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ("to", safe_eth.eth.django.models.EthereumAddressBinaryField()),
                ("log_index", models.PositiveIntegerField()),
                ("encrypt_key_hash", models.BinaryField(null=True)),
                ("encrypted_amount", models.BinaryField(null=True)),
                (
                    "ethereum_tx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="history.ethereumtx",
                    ),
                ),
            ],
            options={
                "verbose_name": "SRC20 Transfer",
                "verbose_name_plural": "SRC20 Transfers",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["address"], name="history_src_address_66afcc_idx"
                    ),
                    models.Index(
                        fields=["_from", "timestamp"],
                        name="history_src__from_778e52_idx",
                    ),
                    models.Index(
                        fields=["to", "timestamp"], name="history_src_to_f7b4a4_idx"
                    ),
                    models.Index(
                        fields=["_from", "address"], name="history_src__from_8863f2_idx"
                    ),
                    models.Index(
                        fields=["to", "address"], name="history_src_to_1360f8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ethereum_tx", "log_index"),
                        name="unique_src20_transfer_index",
                    )
                ],
            },
        ),
        migrations.RunPython(
            create_src20_indexing_status,
            reverse_code=remove_src20_indexing_status,
        ),
    ]
