# Generated by Django 5.2.11 on 2026-09-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0100_safelaststatus_module_guard_safestatus_module_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HederaSafeTransferCursor',
            fields=[
                ('safe_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hedera_transfer_cursor', serialize=False, to='history.safecontract')),
                ('hedera_account_id', models.CharField(blank=True, max_length=32, null=True)),
                ('last_consensus_timestamp', models.CharField(blank=True, max_length=32, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
