# Generated by Django 5.2.11 on 2026-10-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0101_hederasafetransfercursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="ethereumtx",
            name="hedera_transaction_id",
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
